//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "rental_subscription")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_collection: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub item_name: String,
    #[sea_orm(column_type = "Double")]
    pub price: f64,
    pub notificate: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
